language: java

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9

install: mvn -U verify clean --fail-never --quiet -DskipTests -Dinvoker.skip

script:  mvn -U verify --fail-at-end

notifications:
  email: false

matrix:
  fast_finish: true

after_success:
  - ci/deploy-snapshot.sh

sudo: false
before_cache:
  - shopt -s globstar && rm -fr $HOME/.m2/**/*-SNAPSHOT/
  - shopt -s globstar && rm -fr target/it-repo/**/*-SNAPSHOT/
cache:
  directories:
    - $HOME/.m2
    - target/it-repo
